language: java
jdk: openjdk11
#addons:
#  apt:
#    packages:
#      - oracle-java8-installer  # https://github.com/travis-ci/travis-ci/issues/3259

# This skips the mvn install that is otherwise run (implausibly, the setting has to be "true")
# https://docs.travis-ci.com/user/customizing-the-build/#Skipping-the-Installation-Step
install: true

# define the order of the stages:
stages:
  # - deploy_only_vsp
  #  - package
  - test

script:
  - mvn install --update-snapshots --batch-mode --also-make --projects ${MODULE} -DskipTests && cd ${TRAVIS_BUILD_DIR}/${MODULE} && mvn failsafe:integration-test failsafe:verify -B -Dmaven.test.redirectTestOutputToFile -Dmatsim.preferLocalDtds=true --fail-at-end

jobs:
  include:
    #    - stage: package
    #      script: mvn package -B -Dmaven.test.redirectTestOutputToFile -Dmatsim.preferLocalDtds=true --fail-at-end
    # - stage: deploy_only_vsp
    #   script: "cd vsp && mvn --settings ../.travis.settings.xml -B clean failsafe:integration-test failsafe:verify -Dmaven.test.redirectTestOutputToFile deploy"
    #   skip_cleanup: true
    #   if: branch = master
    # (vsp is now a contrib)

env:
  global:
    - MAVEN_OPTS="-Xmx2g"
  matrix:
    # sorted from longest to shortest (to minimise the overall test stage duration)
    - MODULE=ikaddoura      # 28 min 51 sec
    - MODULE=tthunig        # 10 min 34 sec
    - MODULE=kai            # 8 min 39 sec
    - MODULE=dziemke        # 4 min 35 sec
    - MODULE=kturner        # 3 min 31 sec
    - MODULE=vspshk         # 2 min 54 sec
    - MODULE=gleich         # 2 min 52 sec
    - MODULE=stockholm      # 2 min 27 sec
    - MODULE=gunnar         # 2 min 25 sec
    - MODULE=vsptelematics  # 2 min 15 sec
    - MODULE=kairuns        # 2 min 4 sec
    - MODULE=lu             #

cache:
  directories:
    - $HOME/.m2

